env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "80:82"
  timeout: 4s
  idle_timeout: 30s
  user: "Shabby8574"
db:
  username: "url-shortener"
  host: "db"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
